#ifndef GAME_CONFIGURATION_H
#define GAME_CONFIGURATION_H
#define PLANET_COUNT 12
#define CITY_PER_PLANET 300
#define TOTAL_CITIES 3600
#define MAXIMUM_NPC_COUNT 128
#define MAXIMUM_SHADOW_COUNT 100
#define MAXIMUM_LEVEL 9999
#define MAXIMUM_QUEST_COUNT 500
#define MAP_WIDTH 64
#define MAP_HEIGHT 64
#define SPRITE_SIZE_32 32
#define SPRITE_FRAMES_PER_DIRECTION 4
#define SPRITE_DIRECTIONS 4
#define TILE_SIZE_8 8
#endif